@startuml
autonumber
Participant "User"  as user
Participant "Merchant / PSP"  as merchant
Participant "Browser"  as browser
Participant "Payment Handler" as handler
Participant "Token Service Provider" as tsp

user --> merchant : Buy
merchant --> browser : pr.show()
browser --> browser : Match handlers
browser --> user : Display handlers
user --> browser: Select handler
browser --> handler: Launch

== Within the Payment Handler ==
handler --> user : Display cards
user --> handler : Select card
handler --> tsp : Request token and other data
note right
Depends on Implementation:
- Communication with key provider
- Management and validation of key
- Generation and encryption of data
end note
tsp --> handler : Return data 
handler --> browser : Return TokenizedCardResponse
== End of Payment Handler Control ==
browser --> merchant : Return TokenizedCardResponse
== End of Payment Request API ==

@enduml
