@startuml
autonumber
Participant "Merchant / PSP"  as merchant
Participant "Browser"  as browser
Participant "User"  as user
Participant "Payment Handler" as handler
Participant "Token Service Provider" as tsp

merchant --> browser : Provide checkout page
browser --> user : Display checkout page
user --> browser : Push buy button, triggering pr.show()
browser --> user : Display handlers
user --> browser: Select handler
browser --> handler: Launch

== Within the Payment Handler ==
handler --> user : Display cards
user --> handler : Select card
handler --> tsp : Request token and other data
note right
Depends on Implementation:
- Communication with key provider
- Management and validation of key
- Generation and encryption of data
end note
tsp --> handler : Return data 
handler --> browser : Return TokenizedCardResponse
== End of Payment Handler Control ==
browser --> merchant : Return TokenizedCardResponse
== End of Payment Request API ==

@enduml
